= Lab Setup

This lab environment is pre-configured to ensure you can focus on learning and
performing the key tasks without worrying about initial setup. Below are the
details of the setup and resources provided.


== Pre-Configured Items:

* The Ansible Automation Platform controller is already set up.
* The required Execution Environment (`Day2 EE`) has been pre-created with the `redhat.openshift` and `redhat.openshift_virtualization` collections.
* Necessary credentials to access the Virtual Machines are pre-configured in the AAP controller.
* All VMs are running at the start of the lab.

== OpenShift Environment Details:
* Console URL: link:{openshift_cluster_console_url}[{openshift_cluster_console_url}, window="_blank"]
* Username: {openshift_cluster_admin_username}
* Password: {openshift_cluster_admin_password}

== Ansible Automation Platform Environment Details:
* AAP Dashboard: link:{aap_controller_web_url}[{aap_controller_web_url}, window="_blank"]
* Username: {aap_controller_admin_user}
* Password: {aap_controller_admin_password}

== VSCode and Lab Files Overview

Throughout the lab, you will create or update the following files to complete
the exercises:

* `tasks/main.yml`: For calling the appropriate stop, start, and restart tasks.
* `tasks/stop_vm.yml`: For stopping the VM.
* `tasks/start_vm.yml`: For starting the VM.
* `tasks/restart_vm.yml`: For restarting the VM.
* `tasks/snapshot_vms.yml`: Creating Snapshot of the VM.
* `tasks/restore_vm_snapshots.yml`: Restore VM from Snapshot.
* `manage_vm_playbook`: A playbook to run the stop/start/restart tasks.
* `patch_vm_playbook.yml`: A playbook to run the security updates of the RHEL VMs.

To create these files, you will use the Visual Studio Code editor.

* VSCode URL: link:{codeserver_url}[{codeserver_url}, window="_blank"]
* Password: {codeserver_password}

With this setup, you’re ready to dive into the lab and focus on automating Day 2
operations for VMs on OpenShift Virtualization.
